In [ ]:
import numpy as np
from tensorflow import keras
from tensorflow.keras import layers


#### Prepare data

# Model / data parameters
num_classes = 10
input_shape = (28, 28, 1)

# Load the data and split it between train and test sets
(x_train, y_train), (x_test, y_test) = keras.datasets.mnist.load_data()

# Scale images to the [0, 1] range
x_train = x_train.astype("float32") / 255
x_test = x_test.astype("float32") / 255
# Make sure images have shape (28, 28, 1)
x_train = np.expand_dims(x_train, -1) #lisää yksi ulottuvuus = grayscale
x_test = np.expand_dims(x_test, -1)
print("x_train shape:", x_train.shape)
print(x_train.shape[0], "train samples")
print(x_test.shape[0], "test samples")

print("y_train beofore convert:")
print(y_train)
##### Convert class vectors to binary class matrices
y_train = keras.utils.to_categorical(y_train, num_classes)    #muokkaa todennäköisyydet binäärisiksi 10x0.0 ... 1.0 | 1 = 0,1,0,0,0,0,0,0,0,0
y_test = keras.utils.to_categorical(y_test, num_classes)      #muokkaa todennäköisyydet binäärisiksi 10x0.0 ... 1.0

print("y_train after conver:")
print(y_train)

#Build model

model = keras.Sequential(
    [
        keras.Input(shape=input_shape),
        layers.Conv2D(32, kernel_size=(3, 3), activation="relu"),   #relu funktio pistää negatiiviset arvot 0. 3x3 + 1 bias arvo = 10. kuva pienenee koska suodatin ei mene kuvan reunojen yli, vaan alkaa keskemmältä
        layers.MaxPooling2D(pool_size=(2, 2)),                      #kahdesta rivistä ja sarakkeesta maksimi arvo -> kuva puolittuu. laskenta tehon tarve myös pienentyy tässä samalla                
        layers.Conv2D(64, kernel_size=(3, 3), activation="relu"),   #px size = 11x11, kuvia 64, parametrejä 18496
        layers.MaxPooling2D(pool_size=(2, 2)),                      #5x5x64
        layers.Flatten(),                                           #serialisoi edellisen tason
        layers.Dropout(0.5),                                        #satunnaisesti vähentää neuroneita serialisoidusta tasosta
        layers.Dense(num_classes, activation="softmax"),            #num_classes = 10
    ]
)

model.summary()

#Train model

batch_size = 128                                                    #monen kuvan yli lasketaan derivaatta, tätä ei pitäisi käyttää jos käyttää kerasta lukemaan datan
epochs = 15                                                         #monta kuvaa kerralla

model.compile(loss="categorical_crossentropy", optimizer="adam", metrics=["accuracy"])  #käännetään yllä oleva malli, loss= virhefunktio -esim gradient descent, optimizer= optimoija, metrics=,

model.fit(x_train, y_train, batch_size=batch_size, epochs=epochs, validation_split=0.1) #tässä nyt sitte ajetaan se malli

#Evaluate trained model

#score = model.evaluate(x_test, y_test, verbose=0)                   #testataan malli
#print("Test loss:", score[0])
#print("Test accuracy:", score[1])

#for i in range(2):
 #kuva = x_test[i]
  #kuva = np.expand_dims(kuva,0)
...


11501568/11490434 [==============================] - 0s 0us/step
x_train shape: (60000, 28, 28, 1)
60000 train samples
10000 test samples
y_train beofore convert:
[5 0 4 ... 5 6 8]
y_train after conver:
[[0. 0. 0. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 1. 0.]]
Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 conv2d (Conv2D)             (None, 26, 26, 32)        320       
                                                                 
 max_pooling2d (MaxPooling2D  (None, 13, 13, 32)       0         
 )                                                               
                                                                 
 conv2d_1 (Conv2D)           (None, 11, 11, 64)        18496     
                                                                 
 max_pooling2d_1 (MaxPoolin

Ellipsis

In [ ]:
#Evaluate trained model
#import tf.math.argmax
score = model.evaluate(x_test, y_test, verbose=0)                   #testataan malli
print("Test loss:", score[0])
print("Test accuracy:", score[1])

kuvanumero=[]

for i in range(1000):   #37 sekuntia meni tuhannella, x60 = nyt ei ole aikaa tämmöselle
  kuva = x_test[i]      #testaus tarkotukseen
  kuva = np.expand_dims (kuva, 0)
  test = y_test[i]
  tulos = model.predict(kuva)
  testI = np.argmax(test)
  tulosI = np.argmax(tulos)       #max value indeksit

  

  if testI != tulosI:
    kuvanumero.append(i)


  #print(test)
  #print(np.argmax(test))
  #print(tulos)
  #print(np.argmax(tulos))
  #print("-----")
print(kuvanumero)


Test loss: 0.02448863908648491
Test accuracy: 0.9912999868392944
[62, 247, 321, 684, 726, 740, 924, 938, 947]
